### ISSUE TITLE
xlsx crash in pycharm CE

### ISSUE THREAD

**Issue by NMiklave** [obiscr/ExcelReader#2]
Using ExcelReader extension on PyCharm 2021.1 CE. Opened an xlsx with 3 pages. First page displays fine, but error reports on opening either of the other two. Crash report is:

`java.lang.IndexOutOfBoundsException: Header row index 0 is lower than first row index 1.
	at cn.hutool.poi.excel.ExcelReader.read(ExcelReader.java:283)
	at cn.hutool.poi.excel.ExcelReader.readAll(ExcelReader.java:265)
	at com.chesterccw.excelreader.util.ResolveData.resolve(ResolveData.java:120)
	at com.chesterccw.excelreader.util.ResolveData.resolve(ResolveData.java:57)
	at com.chesterccw.excelreader.ui.MyToolWindow.loadSheetPaneAt(MyToolWindow.java:112)
	at com.chesterccw.excelreader.ui.MyToolWindow.lambda$initSheetPane$0(MyToolWindow.java:106)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:418)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:269)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:143)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:74)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:622)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:597)
	at com.intellij.ui.components.JBTabbedPane.setSelectedIndex(JBTabbedPane.java:82)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4086)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6649)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by obiscr** [comment]
Yes, there is. Our development team will fix it as soon as possible.

**Comment by obiscr** [comment]
Thanks for the feedback. According to my test situation, it seems that there is a problem with the xls/xlsx files created by some Excel tools, and some have no problems.

To be precise, it seems to be related to the Excel tool that created xls/xlsx. What tool did you use to create the xls/xlsx file, and the version of the tool, can you tell me?

**Comment by NMiklave** [comment]
The sheet was originally made in some version of Windows Excel 2016, but due to a failed hard drive I no longer have the exact version number. More recently (past few months) I have been using LibreOffice Calc to update and make changes to the xlsx file.

Version: 7.1.2.2 / LibreOffice Community
Build ID: 5751006d328844ba3fa6124ed263bbf122f0788a
CPU threads: 12; OS: Linux 5.4; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Calc: threaded

**Comment by obiscr** [comment]
Ok，I was create xls/xlsx with **MS Office 2019** in windows10.
And it's has problems.

For now，I found it's only empty sheet has this problem.
As long as any cell has a value in sheet, this error will not appear.
So， I need do more testing.

**Comment by obiscr** [comment]
This bug will be fixed in version 2.0.7
