### ISSUE TITLE
exception on Pycharm 2021.3.1 CE and plugin version 2.0.8

### ISSUE THREAD

**Issue by gbonline** [obiscr/ExcelReader#7]
With PyChamr CE 2021.3.1 as 
Build #PC-213.6461.77, built on December 28, 2021

Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
and plugin 2.0.8 on window 10 

Opening a xlsx file I got this exception

`java.lang.NullPointerException
	at com.chesterccw.excelreader.ui.MyToolWindow.lambda$initSheetPane$0(MyToolWindow.java:101)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:418)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:269)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:143)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:74)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:622)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:597)
	at com.intellij.ui.components.JBTabbedPane.setSelectedIndex(JBTabbedPane.java:82)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaTabbedPaneUI.lambda$installListeners$1(DarculaTabbedPaneUI.java:139)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by obiscr** [comment]
Thanks for the feedback, could you provide a desensitization case file?

**Comment by gbonline** [comment]
Oh, yes, 
the simple xlsx file that i attach.
I've also installed the csv and rainbow csv plugins
[DATABASE_ESEMPIO.xlsx](https://github.com/obiscr/ExcelReader/files/7833417/DATABASE_ESEMPIO.xlsx)

**Comment by obiscr** [comment]
> Oh, yes, the simple xlsx file that i attach. I've also installed the csv and rainbow csv plugins [DATABASE_ESEMPIO.xlsx](https://github.com/obiscr/ExcelReader/files/7833417/DATABASE_ESEMPIO.xlsx)
![issue7](https://user-images.githubusercontent.com/28687074/149619428-8753a44d-1bb0-4b52-9f90-7914c29d9197.gif)
I used the file you provided and found no problems. Could you provide stable steps to reproduce the problem? Thank you!

**Comment by gbonline** [comment]
Hi, I dont' know why I've the exception. I've done a little video record to show you what happend. 
The exception occur only the first time I double click/open the xlsx file

https://user-images.githubusercontent.com/3273873/149625681-a286765b-8cfc-4569-93a2-30bd5add491e.mp4

**Comment by obiscr** [comment]
> Hi, I dont' know why I've the exception. I've done a little video record to show you what happend. 
> 
> The exception occur only the first time I double click/open the xlsx file
> 
> 
> 
> https://user-images.githubusercontent.com/3273873/149625681-a286765b-8cfc-4569-93a2-30bd5add491e.mp4
> 
> 
> 
> 
> 
> 

Ok, I'll try it first and see if I can reproduce it.

**Comment by obiscr** [comment]
> Hi, I dont' know why I've the exception. I've done a little video record to show you what happend. The exception occur only the first time I double click/open the xlsx file
> 
>  ice_video_20220115-151106.mp4

A new version will be updated soon, please try again. I still haven't had this problem in my tests.
